import 'dart:async';

import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';

import '../backend/health_data_repository.dart';
import '../services/background_service.dart';

class PostureAnalysisPage extends StatefulWidget {
  const PostureAnalysisPage({super.key});
  @override State<PostureAnalysisPage> createState() => _PostureAnalysisPageState();
}

class _PostureAnalysisPageState extends State<PostureAnalysisPage> {
  static const green = Color(0xFF42D2A7), teal = Color(0xFF45C4D0), background = Color(0xFFF4F9F7), text = Color(0xFF263B37), muted = Color(0xFF7D8D89), line = Color(0xFFE8EFEC), mint = Color(0xFFE8F8F1), orange = Color(0xFFFFA62B), red = Color(0xFFFF6B6B), purple = Color(0xFF9B8AFB);
  StreamSubscription? _statusSubscription;
  bool loading = true;
  String? error;
  List<Map<String, dynamic>> daily = [];
  final live = <String, int>{'hunch': 0, 'neck': 0, 'wrist': 0, 'tooClose': 0, 'lowLight': 0};

  @override void initState() { super.initState(); _listenToService(); _load(); }
  @override void dispose() { _statusSubscription?.cancel(); super.dispose(); }
  void _listenToService() {
    _statusSubscription = BackgroundMonitorService.statusStream.listen((data) {
      if (!mounted || data == null) return;
      final payload = data['metrics'] is Map ? Map<dynamic, dynamic>.from(data['metrics']) : data;
      setState(() { for (final key in live.keys) { final value = payload[key]; live[key] = value is num ? value.toInt() : (value == null ? live[key]! : int.tryParse(value.toString()) ?? live[key]!); } });
    });
  }
  Future<void> _load() async {
    if (mounted) setState(() { loading = true; error = null; });
    try {
      final rows = await HealthDataRepository.instance.getDailyMetrics(days: 7);
      rows.sort((a,b) => DateTime.parse(a['date'].toString()).compareTo(DateTime.parse(b['date'].toString())));
      if (mounted) setState(() { daily = rows; loading = false; });
    } catch (e) { if (mounted) setState(() { loading = false; error = 'بارگذاری تاریخچه سلامت با مشکل مواجه شد.'; }); debugPrint('[PostureAnalysisPage] $e'); }
  }
  double _number(Map<String,dynamic> row,String key) { final v=row[key]; return v is num ? v.toDouble() : double.tryParse('$v') ?? 0; }
  String _duration(double minutes) { if(minutes<1)return '${(minutes*60).round()}ث'; if(minutes<60)return '${minutes.round()}د'; final h=minutes~/60,m=minutes.round()%60; return m==0?'${h}س':'${h}س ${m}د'; }
  Map<String,dynamic>? get today { if(daily.isEmpty)return null; final n=DateTime.now(); for(final r in daily.reversed){final d=DateTime.parse(r['date'].toString());if(d.year==n.year&&d.month==n.month&&d.day==n.day)return r;} return daily.last; }
  double _todayRisk(){final r=today;if(r==null)return 0;return _number(r,'neck')+_number(r,'hunch')+_number(r,'wrist')+_number(r,'tooClose')+_number(r,'badLight');}
  int _score(){final r=today;final stored=r==null?0:_number(r,'health_score');return stored>0?stored.round().clamp(0,100):(100-_todayRisk()*.8).round().clamp(0,100);}
  Widget _card({required Widget child,EdgeInsets padding=const EdgeInsets.all(17)})=>Container(padding:padding,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),border:Border.all(color:line),boxShadow:const[BoxShadow(color:Color(0x08000000),blurRadius:18,offset:Offset(0,6))]),child:child);
  Widget _header()=>LayoutBuilder(builder:(_,c)=>Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('وضعیت بدن',style:TextStyle(color:text,fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text('داده‌های پایش را به زبان ساده دنبال کن.',maxLines:c.maxWidth<340?3:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:muted,fontSize:11))])),const SizedBox(width:10),Container(width:46,height:46,decoration:const BoxDecoration(color:mint,shape:BoxShape.circle),child:const Icon(Icons.accessibility_new_rounded,color:green,size:26))]));
  Widget _liveCard(){final total=live.values.fold<int>(0,(s,v)=>s+v);return Container(padding:const EdgeInsets.all(17),decoration:const BoxDecoration(gradient:LinearGradient(colors:[green,teal]),borderRadius:BorderRadius.all(Radius.circular(22))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[const Icon(Icons.radar_rounded,color:Colors.white,size:23),const SizedBox(width:8),const Expanded(child:Text('پایش زنده',style:TextStyle(color:Colors.white,fontSize:14,fontWeight:FontWeight.w900))),Container(width:8,height:8,decoration:const BoxDecoration(color:Colors.white,shape:BoxShape.circle))]),const SizedBox(height:6),Text(total==0?'هنوز هشدار زنده‌ای ثبت نشده.':'در حال ثبت الگوهای بدنی و فاصله از صفحه.',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white70,fontSize:10)),const SizedBox(height:14),LayoutBuilder(builder:(_,c){final compact=c.maxWidth<430;final values=[('قوز',live['hunch']!,Icons.airline_seat_recline_normal_rounded),('گردن',live['neck']!,Icons.accessibility_new_rounded),('مچ',live['wrist']!,Icons.back_hand_rounded),('فاصله',live['tooClose']!,Icons.phone_android_rounded)];if(compact)return Wrap(spacing:7,runSpacing:7,children:values.map((x)=>_livePill(x.$1,x.$2,x.$3)).toList());return Row(children:values.map((x)=>Expanded(child:_livePill(x.$1,x.$2,x.$3))).toList());})]));}
  Widget _livePill(String title,int value,IconData icon)=>Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:8),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.15),borderRadius:BorderRadius.circular(14)),child:Row(mainAxisSize:MainAxisSize.min,children:[Icon(icon,color:Colors.white,size:15),const SizedBox(width:5),Text('$title ${value}s',style:const TextStyle(color:Colors.white,fontSize:9,fontWeight:FontWeight.w800))]));
  Widget _todayCard(){final r=today,s=_score();if(r==null)return _card(child:const Row(children:[Icon(Icons.insights_rounded,color:green),SizedBox(width:10),Expanded(child:Text('هنوز داده روزانه‌ای برای نمایش وجود ندارد.',style:TextStyle(color:muted,fontSize:11)))]));return _card(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[LayoutBuilder(builder:(_,c)=>Row(children:[const Expanded(child:Text('خلاصه امروز',style:TextStyle(color:text,fontSize:15,fontWeight:FontWeight.w900))),SizedBox(width:52,height:52,child:Stack(alignment:Alignment.center,children:[CircularProgressIndicator(value:s/100,strokeWidth:6,backgroundColor:mint,valueColor:const AlwaysStoppedAnimation(green)),Text('$s',style:const TextStyle(color:text,fontSize:13,fontWeight:FontWeight.w900))]))])),const SizedBox(height:12),LayoutBuilder(builder:(_,c){final items=[('گردن',_duration(_number(r,'neck')),Icons.accessibility_new_rounded,teal),('قوز',_duration(_number(r,'hunch')),Icons.airline_seat_recline_normal_rounded,green),('مچ',_duration(_number(r,'wrist')),Icons.back_hand_rounded,orange),('فاصله کم',_duration(_number(r,'tooClose')),Icons.phone_android_rounded,red),('نور کم',_duration(_number(r,'badLight')),Icons.wb_sunny_outlined,purple)];final cols=c.maxWidth<360?1:(c.maxWidth<520?2:3);final width=cols==1?c.maxWidth:(c.maxWidth-(cols-1)*8)/cols;return Wrap(spacing:8,runSpacing:8,children:items.map((x)=>SizedBox(width:width,child:_smallMetric(x.$1,x.$2,x.$3,x.$4))).toList());})]));}
  Widget _smallMetric(String title,String value,IconData icon,Color color)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:11),decoration:BoxDecoration(color:background,borderRadius:BorderRadius.circular(15)),child:Row(children:[Icon(icon,color:color,size:17),const SizedBox(width:7),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:muted,fontSize:8)),const SizedBox(height:2),Text(value,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(color:text,fontSize:11,fontWeight:FontWeight.w900))]))]));
  Widget _chart(){if(daily.length<2)return _card(child:const Row(children:[Icon(Icons.show_chart_rounded,color:teal),SizedBox(width:9),Expanded(child:Text('با چند روز داده، روند هفتگی اینجا نمایش داده می‌شود.',style:TextStyle(color:muted,fontSize:11)))]));final spots=<FlSpot>[];for(var i=0;i<daily.length;i++){final r=daily[i];spots.add(FlSpot(i.toDouble(),_number(r,'neck')+_number(r,'hunch')+_number(r,'wrist')));}final maxY=spots.map((e)=>e.y).fold<double>(1,(a,b)=>a>b?a:b);return _card(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('روند فشار بدنی',style:TextStyle(color:text,fontSize:15,fontWeight:FontWeight.w900)),const SizedBox(height:4),const Text('مجموع زمان گردن، قوز و مچ در هفت روز اخیر',style:TextStyle(color:muted,fontSize:10)),const SizedBox(height:18),SizedBox(height:190,child:LineChart(LineChartData(minX:0,maxX:(spots.length-1).toDouble(),minY:0,maxY:maxY*1.15,gridData:FlGridData(show:true,drawVerticalLine:false,getDrawingHorizontalLine:(_)=>const FlLine(color:line,strokeWidth:1)),borderData:FlBorderData(show:false),titlesData:FlTitlesData(topTitles:const AxisTitles(sideTitles:SideTitles(showTitles:false)),rightTitles:const AxisTitles(sideTitles:SideTitles(showTitles:false)),leftTitles:const AxisTitles(sideTitles:SideTitles(showTitles:true,reservedSize:32)),bottomTitles:AxisTitles(sideTitles:SideTitles(showTitles:true,reservedSize:26,interval:1,getTitlesWidget:(v,m){final i=v.round();if(i<0||i>=daily.length)return const SizedBox.shrink();final d=DateTime.parse(daily[i]['date'].toString());return SideTitleWidget(meta:m,child:Text('${d.month}/${d.day}',style:const TextStyle(color:muted,fontSize:8)));})),),lineBarsData:[LineChartBarData(spots:spots,isCurved:true,color:teal,barWidth:3,dotData:const FlDotData(show:true),belowBarData:BarAreaData(show:true,color:mint))]))),]));}
  Widget _breakdown(){if(daily.isEmpty)return const SizedBox.shrink();return _card(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('جزئیات روزها',style:TextStyle(color:text,fontSize:15,fontWeight:FontWeight.w900)),const SizedBox(height:10),...daily.reversed.map((r){final d=DateTime.parse(r['date'].toString());final label=d.year==DateTime.now().year&&d.month==DateTime.now().month&&d.day==DateTime.now().day?'امروز':'${d.month}/${d.day}';final score=_number(r,'health_score').round();final total=_number(r,'neck')+_number(r,'hunch')+_number(r,'wrist');return Padding(padding:const EdgeInsets.symmetric(vertical:7),child:Row(children:[Container(width:34,height:34,decoration:const BoxDecoration(color:mint,shape:BoxShape.circle),child:const Icon(Icons.calendar_today_rounded,color:green,size:16)),const SizedBox(width:9),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(label,style:const TextStyle(color:text,fontSize:11,fontWeight:FontWeight.w800)),const SizedBox(height:2),Text('فشار بدنی: ${_duration(total)}',style:const TextStyle(color:muted,fontSize:9))])),Text(score>0?'$score':'—',style:const TextStyle(color:green,fontSize:13,fontWeight:FontWeight.w900))]));})]));}
  @override Widget build(BuildContext context)=>Directionality(textDirection:TextDirection.rtl,child:Scaffold(backgroundColor:background,body:RefreshIndicator(color:green,onRefresh:_load,child:ListView(physics:const AlwaysScrollableScrollPhysics(parent:BouncingScrollPhysics()),padding:const EdgeInsets.fromLTRB(18,14,18,30),children:[_header(),const SizedBox(height:14),_liveCard(),const SizedBox(height:14),if(loading)const Center(child:Padding(padding:EdgeInsets.all(24),child:CircularProgressIndicator(color:green))),if(error!=null)_card(child:Row(children:[const Icon(Icons.error_outline_rounded,color:red),const SizedBox(width:8),Expanded(child:Text(error!,style:const TextStyle(color:muted,fontSize:10)))])),if(!loading)...[_todayCard(),const SizedBox(height:14),_chart(),const SizedBox(height:14),_breakdown()]]))));
}