name: monitor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  camera: ^0.10.0
  flutter_local_notifications: ^18.0.1
  flutter_background_service: ^5.1.0
  permission_handler: ^11.1.0
  flutter_overlay_window: ^0.4.5
  sensors_plus: ^6.1.1
  google_mlkit_pose_detection: ^0.13.0
  nsfw_detector_flutter: ^2.0.2
  fl_chart: ^1.0.0
  mailer: ^6.5.0
  provider: ^6.1.5
  supabase_flutter: ^2.15.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  chewie: ^1.15.0
  video_player: ^2.14.0
  shamsi_date: ^1.1.1
  audioplayers: ^6.8.1
  record: ^7.1.1
  file_picker: ^12.0.0
  just_audio: 0.10.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  monitor_channels:
    path: ./monitor_channels

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

fonts:
  - family: Vazirmatn
    fonts:
      - asset: assets/fonts/Vazirmatn-Regular.ttf
      - asset: assets/fonts/Vazirmatn-Bold.ttf
        weight: 700

flutter:
  uses-material-design: true
  assets:
    - assets/wrist_neck.png
    - assets/logo.png
    - assets/slouched.png
    - assets/straight.png
    - assets/history.png
    - assets/eyeComfort.png
    - assets/meditate.png
    - assets/backPosture.png
    - assets/icons/default.png
    - assets/icons/hunch.png
    - assets/icons/neck_tilt.png
    - assets/icons/too_close.png
    - assets/sounds/too_close.wav
    - assets/sounds/neck.wav
    - assets/sounds/hunch.wav
    - assets/sounds/wrist.wav
    - assets/sounds/low_light.wav
